name: Build JPEG XL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: echo "Assuming [cmake, libjpeg, libpng, parallel] are already installed" &&
           brew install clang-format coreutils doxygen giflib ninja  sdl2 zlib
    - name: Build
      run: cd third_party/jpeg-xl &&
           export CMAKE_PREFIX_PATH=`brew --prefix giflib`:`brew --prefix libjpeg`:`brew --prefix libpng`:`brew --prefix sdl2`:`brew --prefix zlib` &&
           SKIP_TEST=1 ./ci.sh release -DCMAKE_FIND_FRAMEWORK=NEVER
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: third_party/jpeg-xl/build/tools